import os  
import datetime  

# Code was generated by Ernie Bot (文心一言) and modified by me.

ctime = {}
for root, _, files in os.walk('data\\sr_bwiki_code'):  
    for file in files:  
        if file.endswith('.txt'):  
            file_path = os.path.join(root, file)  
            creation_time = os.path.getctime(file_path)  
            readable_time = datetime.datetime.fromtimestamp(creation_time).strftime('%Y-%m-%d')  

            trunc_filename = file.replace('.txt', '').replace('_', '\_')
            if readable_time not in ctime:
                ctime.update({readable_time: []})
            ctime[readable_time].append(trunc_filename)

tbl_cells = ''
for time, name in ctime.items():
    name_lst = "、\n".join(name)
    tbl_cells += f'[{time}], [{name_lst}],\n'

tbl = f'''
#align(center)[
#figure(
caption: [|《崩坏：星穹铁道》主线剧情各个小节访问时间。在文本收集过程中，由于我是直接复制网页的源代码，
所以文件的创建时间可以认为是网页访问时间。],
kind: "表",
supplement: "表",
)[
#table(
stroke: none,
columns: (auto, auto),
inset: 10pt,
align: horizon,
table.hline(),
table.header(
[创建时间], [文件名],
),
{tbl_cells}
)
]<tbla1>
]
'''
print(tbl)